# Generated by Django 3.0.7 on 2020-06-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nstars', models.FloatField()),
                ('nreviews', models.IntegerField()),
                ('jobs_completed', models.FloatField()),
                ('on_budget', models.FloatField()),
                ('on_time', models.FloatField()),
                ('repeat_hire_rate', models.FloatField()),
                ('description', models.TextField()),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('bider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.MCandidate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.MProject')),
            ],
        ),
    ]
