# Generated by Django 3.0.7 on 2020-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbids',
            name='currency',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='mbids',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mbids',
            name='ndays',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='mbids',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
