# Generated by Django 3.0.7 on 2020-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20200624_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproject',
            name='url',
            field=models.CharField(max_length=220),
        ),
    ]
