# Generated by Django 3.0.7 on 2020-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20200624_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbids',
            name='ndays',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
