# Generated by Django 3.0.7 on 2020-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_auto_20200624_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcandidate',
            name='jobs_completed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcandidate',
            name='on_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcandidate',
            name='on_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcandidate',
            name='repeat_hire_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
